User's Guide
------------

This part focuses on instructions for Cron jobs management with Plan.

.. toctree::
   :maxdepth: 2
   
   installation
   quickstart
   tutorial
   job_definition
   plan_definition
   job_types
   run_types
   commands


API Reference
-------------

This part focuses on information on a specific function, class or method.

.. toctree::
   :maxdepth: 2

   api


Additional Stuff
----------------

Changelog and license here if you are interested.

.. toctree::
   :maxdepth: 2

   python3
   changelog
   license
